name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: linux

    steps:
    - uses: actions/checkout@v3
    - name: compile
      run:  gcc main.c -o main.sh
    - name: run
      run: ./main.sh
